baseURL = 'http://matthijsjanssens.github.io/'
languageCode = 'en-us'
title = 'Matthijs Janssens'
theme = 'PaperMod'
enableEmoji = true

[params]
env = 'production'
hideSummary = true
comments = true
defaultTheme = 'auto'

[params.homeInfoParams]
Title = 'Hi there ğŸ‘‹ğŸ»'
Content = """
Welcome to my blog!

My name is **Matthijs Janssens** *(ma-tess ian-sense)*.

I'm a seasoned **technical artist** working in **videogames** with a background in **music composition**.

Into gamedev, felted pianos, tea, chess and toads.
"""

[[params.socialIcons]]
name = 'twitter'
url = 'https://twitter.com/matthijsjanssns'

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/matthijsjanssens'

[[params.socialIcons]]
name = 'linkedin'
url = 'https://www.linkedin.com/in/matthijs-janssens-23858a59/'

[[params.socialIcons]]
name = 'rss'
url = 'https://matthijsjanssens.github.io/index.xml'

[outputs]
home = [ 'HTML', 'RSS', 'JSON' ]
