baseURL = 'http://matthijsjanssens.github.io/'
languageCode = 'en-us'
title = 'Matthijs Janssens'
theme = ['hugo-notice', 'PaperMod']
enableEmoji = true
googleAnalytics = 'G-S25PLFZEW4'
pygmentsUseClasses = true

[params]
hideSummary = true
comments = true
defaultTheme = 'auto'
ShowCodeCopyButtons = true
disableThemeToggle = false

[params.assets]
disableHLJS = true
disableFingerprinting = false 
# https://github.com/adityatelange/hugo-PaperMod/issues/89#issuecomment-736549907

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
noClasses = false

[params.homeInfoParams]
Title = "Hi there, I'm Matt ğŸ‘‹ğŸ»"
Content = """
**Lead Technical Artist** at [**Studio Gobo**](https://www.studiogobo.com/) in Brighton ğŸ‡¬ğŸ‡§

Welcome to my personal **game development blog**
"""

[[params.socialIcons]]
name = 'instagram'
url = 'https://www.instagram.com/matts.janss/'

[[params.socialIcons]]
name = 'twitter'
url = 'https://twitter.com/matthijsjanssns'

[[params.socialIcons]]
name = 'spotify'
url = 'https://open.spotify.com/user/117013342?si=92b87c0e75b744b9'

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/matthijsjanssens'

[[params.socialIcons]]
name = 'linkedin'
url = 'https://www.linkedin.com/in/matthijs-janssens-23858a59/'

[[params.socialIcons]]
name = 'rss'
url = 'https://matthijsjanssens.github.io/index.xml'

[outputs]
home = [ 'HTML', 'RSS', 'JSON' ]
